# 단일 표본 t 검정

- txt 파일의 데이터를 읽어서 float형으로 형변환
- 정규성 검정
    - kstest를 활용해 정규성 검정 진행
- 단일표본 t 검정
    - p-value < 0.05 : 귀무가설 기각, 대립가설 채택, 통계적으로 유의미하다.
    - p-value > 0.05 : 귀무가설 채택, 대립가설 기각

## 정규성 검정
- 수집 표본 데이터가 정규분포를 따르는지 검증한다.
### 정규성 검정의 가설
- 귀무 가설: 수집 표본의 데이터는 정규성을 따른다.
- 대립 가설: 수집 표본 데이터는 정규성을 따르지 않는다.

In [1]:
with open("datas2/성인여성_키_데이터1.txt", "r", encoding="utf8") as f:
    data = f.read().split('\n')
    # print(data)
    data = list(map(float, data))
    print(data)

[163.94, 162.48, 164.29, 166.3, 162.26, 162.26, 166.43, 164.57, 161.72, 164.05, 161.73, 161.73, 163.36, 158.4, 158.83, 161.51, 160.47, 163.52, 160.71, 159.55, 166.17, 162.28, 162.96, 159.52, 161.55, 163.06, 160.15, 163.66, 161.42, 162.13]

In [4]:
from scipy import stats
import numpy as np

# 평균과 표준편차 계산
mean_value = np.mean(data)
std_dev = np.std(data, ddof=0)  # 모집단 표준편차(기본 설정)

mean_value, std_dev

(np.float64(162.36700000000002), np.float64(2.0354559685731335))

## 가설 설정
- 귀무가설: 표본 데이터의 평균은 163과 같다.
- 대립가설: 표본 데이터의 평균은 163과 다르다.

## 정규성 검정
- 방법1: KS-test
- 방법2: Shapiro-Wilk 검정
    - scipy.stats.shapiro()

In [7]:
#  KS-test는 주어진 표본 데이터가 정규분포를 따르는지 검정한다.

# stats.norm.cdf: 비교 대상이 되는 이론적인 분포를 지정 ('norm'은 정규분포)
# args=(np.mean(data), np.std(data, ddof=0)): 표본 데이터의 평균과 표준편차를 사용하여 정규분포의 모수 설정
mean_val = np.mean(data)
std_val = np.std(data, ddof=1)

result = stats.kstest(data, stats.norm.cdf, args=(mean_val, std_val))
print(result.pvalue)

0.9486730178962828

[결과 해석]

- p-value > 0.05: 귀무가설을 기각하지 못함 → 데이터가 정규분포를 따르지 않는다 라고 말할 충분한 증거가 없음.
- p-value <= 0.05: 귀무가설을 기각 → 데이터는 정규분포를 따르지 않는다고 판단.

In [8]:
stats.shapiro(data)

ShapiroResult(statistic=np.float64(0.9750912943880133), pvalue=np.float64(0.6854198354912403))

[해설]

p-value > 0.05 : 정구분포를 따르지 않는다라고 말할 충분한 증거가 없음. 귀무가설 기각하지 않음

## 검정 하기

In [ ]:
# 단일 표본 t 검정 수행
# 검중 수치 = 163, 귀무가설 평균키는 163이다.

print(stats.ttest_1samp(data, 163))

TtestResult(statistic=np.float64(-2.979804412662668), pvalue=np.float64(0.00651044533584796), df=np.int64(24))

[결과 해석]

- t-통계량
    - statistic = -1.6747 : t-값이 음수인 것은 표본 평균이 163보다 작다는 것을 의미
    - 절댓값이 클수록 귀무가설을 기각할 가능성이 커짐
- p-value
    - 유의수준 0.05에서 p-value(0.1047) > 0.05 이므로 귀무가설을 기각하지 않음(귀무가설 채택)
    - 표본의 평균이 163과 통계적으로 유의미하게 다르다고 볼 수 없음
- 결론적으로 표본 평균이 163과 다르다고 할 충분한 증거가 없음

# 독립 표본 t 검정
- 두 그룹 A, B반의 점수 차이가 있는지 판단하기

In [10]:
import pandas as pd
import numpy as np

In [11]:
df1 = pd.read_csv("./datas2/반별_점수_type1.csv", encoding = "euc-kr")
# df1 = pd.read_csv("./datas2/반별_점수_type1.csv")
df1.head()

   반  점수
0  A  73
1  A  69
2  A  71
3  A  71
4  A  73

In [12]:
# A반의 데이터만 추출
group_A = df1['점수'].loc[df1['반'] == 'A'].values
# B반의 데이터만 추출
group_B = df1['점수'].loc[df1['반'] == 'B'].values

print(group_A)
print(group_B)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63 56 73 61 55 77 75 65 61 55]

위 두 그룹의 각각의 평균과 표준편차 구하기

In [13]:
import numpy as np

# A반의 평균과 표준 편차
mean_A = np.mean(group_A)
std_A = np.std(group_A, ddof=1)  # 표본 표준 편차 (ddof=1)

# B반의 평균과 표준 편차
mean_B = np.mean(group_B)
std_B = np.std(group_B, ddof=1)  # 표본 표준 편차 (ddof=1)

# 결과 출력
print(f"A반 평균: {mean_A:.2f}, 표준 편차: {std_A:.2f}")
print(f"B반 평균: {mean_B:.2f}, 표준 편차: {std_B:.2f}")

A반 평균: 70.55, 표준 편차: 5.68
B반 평균: 64.10, 표준 편차: 8.28

## 정규성 검정
- KS test or Shapiro-Wilk 검정
- 정규성 검정 가설 수립
    - 영가설: 두 그룹의 표본 데이터는 정규성을 따른다.
    - 대립가설: 두 그룹의 표본 데이터는 정규성을 따르지 않는다.

In [15]:
# group_A와 group_B의 평균과 표준편차를 사용하여 정규성 검정 수행
print(stats.kstest(
  group_A, 
  stats.norm.cdf, 
  args=(np.mean(group_A), np.std(group_A, ddof=1))))

print(stats.kstest(
  group_B, 
  stats.norm.cdf, 
  args=(np.mean(group_B), np.std(group_B, ddof=1))))

KstestResult(statistic=np.float64(0.13310674849448567), pvalue=np.float64(0.8254564220619713), statistic_location=np.float64(73.0), statistic_sign=np.int8(1))
KstestResult(statistic=np.float64(0.15881009358601705), pvalue=np.float64(0.9295432555006241), statistic_location=np.float64(73.0), statistic_sign=np.int8(-1))

[해석]

- p-value >= 0.05 : 귀무가설을 기각지하 없음. 모두 정규 분포를 따른다고 판단

## 등분산성 검정
- 가설 수립
    - 영가설: 두 그룹은 분산이 유사하다(등분산성)
    - 대립가설: 두 그룹은 분산이 유사하지 않다(등분산을 따르지 않는다)

그룹A와 그룹B가 같은 분산 인지 확인하기 위해 levene() 검정 사용

In [16]:
stats.levene(group_A, group_B)

LeveneResult(statistic=np.float64(2.033067087400979), pvalue=np.float64(0.1649640862221014))

[해석]
- p-value >= 0.05: 두 그룹의 분산이 같다(등분산)을 띈다고 볼 수 있음 
- p-value < 0.05: 두 그룹의 분산이 같지않다고 판단할 수 있음

## 독립표본 t 검정 수행
- 가설 수립
    - 영가설: 두 그룹의 표본 평균이 같다.
    - 대립가설: 두 그룹의 표본 평균은 다르다.

In [17]:
# A와 B간에는 차이가 존재함을 확인
# equal_var = True(등분산 만족)
print(stats.ttest_ind(group_A, group_B, equal_var = True))

TtestResult(statistic=np.float64(2.5128526794964134), pvalue=np.float64(0.018010953528937678), df=np.float64(28.0))

[해석]

- p-value < 0.05 : 그룹 A와 그룹 B의 평균 차이가 있다는 것을 알 수 있음
- 통계값이 양수이므로 : A반 학생들의 성적이 더 좋다는 것을 알 수 있음

## Tip. 다른 데이터 포맷의 처리
- A반, B반 두개의 컬럼으로 데이터가 구성되어 있을 경우

In [18]:
df2 = pd.read_csv("datas2/반별_점수_type2.csv", encoding = "euc-kr")
df2.head()

   A반    B반
0  73  63.0
1  69  56.0
2  71  73.0
3  71  61.0
4  73  55.0

In [19]:
# 길이가 달라서 결측이 발생할 수 있으므로, 결측을 제거한 뒤 각 컬럼을 group_A와 group_B에 저장
group_A = df2['A반'].dropna().values
group_B = df2['B반'].dropna().values

In [20]:
print(group_A)
print(group_B)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63. 56. 73. 61. 55. 77. 75. 65. 61. 55.]